### ISSUE TITLE
Update and add interfaces for the puts based on PRIF version 0.4

### ISSUE THREAD

**Issue by ktras** [BerkeleyLab/caffeine#116]
- [ ] `put`
- [ ] `put_indirect`
- [ ] `put_with_notify`
- [ ] `put_indirect_with_notify`
- [ ] `put_with_notify_indirect`
- [ ] `put_indirect_with_notify_indirect`
- [ ] `put_strided`
- [ ] `put_strided_indirect`
- [ ] `put_strided_with_notify`
- [ ] `put_strided_indirect_with_notify`
- [ ] `put_strided_with_notify_indirect`
- [ ] `put_strided_indirect_with_notify_indirect`

**Comment by bonachea** [comment]
duplicate of #119
