### ISSUE TITLE
Add all `prif` interfaces from latest design doc draft (revision 0.2)

### ISSUE THREAD

**Issue by ktras** [BerkeleyLab/caffeine#50]
- [ ] Add all subroutines
- [ ] Add all constants from `iso_fortran_env` module
- [ ] After `iso_fortran_env` module constants are added, remove any `use-stmts` for `iso_fortran_env` and replace references to those constants with the corresponding `prif` constants
- [ ] Add test that invokes all of the `prif` symbols so that the link time errors will occur if something from `prif` is missing from `Caffeine`

**Comment by bonachea** [comment]
This notably includes all of "2.3.2 Constants in ISO_FORTRAN_ENV", which currently all appear to be missing from the implementation

**Comment by bonachea** [comment]
subsumed by #119
