### ISSUE TITLE
add topics coarray, coarray-fortran

### ISSUE THREAD

**Issue by Beliavsky** [BerkeleyLab/caffeine#8]
I suggest adding the topics coarray, coarray-fortran to the About section.

**Comment by rouson** [comment]
@Beliavsky thanks for your interest in Caffeine!  I'll be glad to do this if you can provide more details.  Where is the About section?  Are you proposing the addition of new section to the README.md or referring to a GitHub feature?  If this is something you can add via pull request, please do so.

**Comment by rouson** [comment]
@Beliavsky just after writing the above message, I found the About section.  Done. Thanks for the suggestion!
